#+POSTID: 92
#+DATE: [2017-04-09 Sun 19:44]
#+TITLE: About

Hello stranger! You have reached my personal blog on which you should
expect to find (hopefully) helpfully tutorials on things about and
related to free open source software, free culture, and using libre
tools to get things done.

All the text on this blog is freely redistributable under the terms of
the [[https://creativecommons.org/licenses/by-sa/4.0/][Creative Commons Attribution-ShareAlike 4.0 International (CC
BY-SA 4.0]]). This means you can adapt my posts into new content and
share them if you so wish!  So long as I am credited as the original
author and you do not revoke these freedoms from anyone else.

I write these posts in a markup language called Org-mode which was
originally made for Emacs but has since been re-implemented in other
editors as well (albeit more limited). You can view the source on my
[[https://gitlab.com/taingram/blog/][GitLab]].

I release all of my works under Creative Commons and free software
licenses.

- Bitcoin: 17JSBn8DKXgtb7X1noscvUsj26DrFrc82
