#+TITLE: How to Stay Sane within the Trump 2.0 News Cycle
#+DATE: [2025-02-07 Fri]

Donald Trump has been in office for less than a month and life already
feels extremely chaotic.  The daily new cycle feels fast and insane,
that being their intentional "flood the zone" political strategy.  To
implement as much as possible as quickly as possible to overwhelm any
opposition.  If you have been avoiding the news, or reading this from
the future, this article summarizes the first couple weeks well:

[[https://www.cjr.org/the_media_today/trump_flood_zone_transparency_secrecy_musk.php][Columbia Journalism Review - Is Trump Flooding or Draining the Zone?  Yes. [Feb 3, 2025]​]]

Under this atmosphere it is easy to get overwhelmed by the shear
volume of news and apparent chaos.  In this regard I hope to provide
some recommendations on how I personally am trying to handle life and
stay sane.

* Rest & Reset from the 24-hour News Cycle

It is critical to remember reading the news (and social media) is
_not_ activism.  You personally staying constantly updated will not
make any positive impact on its own.  The urge to stay plugged in is
just draining your mental stamina and feeding the algorithms.

Set limits on when you can access the news and social media.  I
personally check the news throughout my morning and workday.  I check
BlueSky when I get off work, then I try to completely get
off my phone by 7 PM.  I have been trying especially not to check the
social media before bed.

As much as possible your free time should be recharging and living life.
Be with the people you love.  Work on your hobbies, create things!  Do
things that you enjoy, go hiking, get into [[https://play.google.com/store/apps/developer?id=SQUARE+ENIX+Co.,Ltd.&hl=en-US][100+ hour long JRPGs]].
Whatever you need to do.  Do not mindlessly doom scroll.

Beyond that make sure you are getting enough sleep.  Everything is
worse and harder when you are exhausted.  This is something I actively
have to manage as someone who has problems falling asleep and
desperately needs 8+ hours of it.  Limit screens before bed.  I like
to unwind with a book, or at least a very chill game like Dragon
Quest.

* Can Social Media Outrage Actually Do Anything?

Trump has shown he does respond to extremely bad press, economic
shifts, and approval ratings.  If it shown on TV news or negatively
impacts support from his base he has pivoted.  So there is some value
to outrage news, especially if it can generate negative opinion across
the right wing.

Talk to people in your direct life about what is going on and why it
matters.  Especially if they are center or right-leaning.  Their news
media may be completely ignoring or spinning news stories out of
context.  That type of small advocacy can be helpful.

Keep in mind our House Representatives are much more easily swayed by
bad press and polling.  Their elections are coming fast and we need to
make them aware that we are paying attention to their actions.  Find
your House Representative and let them know when you disagree with
their action.  Further let people in your area know what they are
doing.

[[https://www.house.gov/representatives/find-your-representative][Find Your Representative - U.S. House of Representatives]]

* Disclaimer, I'm just some guy

I want to keep the scope of this post limited to news and social media
consumption, as that is something I personally can speak to.  I don't
know how to fix politics in this country.  I am also privileged that I
likely will not be significantly disadvantaged by Trump's policies
(unless he starts a recession or war).  Regardless of your politics
please try to be conscious and empathetic towards the people being
negatively affected by our government's actions.  Consider further if
this is an administration you wish to support.

Please consider contributing to organizations assisting people being
harmed domestically and abroad.  I will try to add additional
organizations as I discover them.

- https://www.aclu.org/
- https://www.rescue.org/
