#+DATE: [2017-04-01 Sat 16:40]
#+TITLE: Audio Popping Fix for Linux
#+TAGS: xps, linux, tlp, laptop

The Dell XPS has been my primary computer for the past couple
months. It has worked great but recently I noticed some audio
crackling when starting/stopping videos and music playback.

* Solution
I [[http://en.community.dell.com/support-forums/laptop/f/3517/t/20006160][found the problem]] was an issue with =tlp= a fantastic little tool
that helps save power on Linux laptops. Issue was it was cutting power
to my audio jack when not in use which caused the loud crackling when
it was turned on and off.

** Check if tlp is running
Run the command
#+BEGIN_SRC bash :results text verbatim
systemctl status tlp
#+END_SRC

Example output:
#+RESULTS:
#+begin_example
● tlp.service - TLP system startup/shutdown
   Loaded: loaded (/usr/lib/systemd/system/tlp.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2017-05-12 00:27:00 EDT; 59min ago
     Docs: http://linrunner.de/tlp
  Process: 1574 ExecStart=/usr/sbin/tlp init start (code=exited, status=0/SUCCESS)
 Main PID: 1574 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/tlp.service

May 12 00:27:00 XPS systemd[1]: Starting TLP system startup/shutdown...
May 12 00:27:00 XPS tlp[1574]: Applying power save settings...done.
May 12 00:27:00 XPS tlp[1574]: Setting battery charge thresholds...done.
May 12 00:27:00 XPS systemd[1]: Started TLP system startup/shutdown.
#+end_example

In the output you should see the 3rd line "=Active: active=" if =tlp=
is running. Otherwise this solution likely won't fix your problem.

** Edit your tlp config

To solve this edit =/etc/default/tlp= (for beginners use "=gksudo
gedit /etc/default/tlp=" or "=sudo nano /etc/default/tlp=").

Change lines:
#+BEGIN_SRC
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
#+END_SRC
To this:
#+BEGIN_SRC
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=0
#+END_SRC
Then restart your computer.

That will stop =tlp= from turning your audio on and off when audio
stops playing. You may loose some slight power savings, but I haven't
noticed anything significant. So it's worth doing just to ditch the
annoying crackling!

* See Also
- [[https://wiki.archlinux.org/index.php/Dell_XPS_13_(9350)#Sound]]
